<a href="https://colab.research.google.com/github/manik2158/capstone-1st-project-/blob/master/Applied_datascience_capstone_week_3%5B2%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np 
import pandas as pd
from bs4 import BeautifulSoup
from sklearn.cluster import KMeans
import requests

In [0]:
data = requests.get('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M').text

In [0]:
soup = BeautifulSoup(data, 'html.parser')

In [0]:
postalCodeList = []
boroughList = []
neighborhoodList = []

In [0]:
soup.find('table').find_all('tr')

# find all the rows of the table
soup.find('table').find_all('tr')

# for each row of the table, find all the table data
for row in soup.find('table').find_all('tr'):
    cells = row.find_all('td')

In [0]:
for row in soup.find('table').find_all('tr'):
    cells = row.find_all('td')
    if(len(cells) > 0):
        postalCodeList.append(cells[0].text)
        boroughList.append(cells[1].text)
        neighborhoodList.append(cells[2].text.rstrip('\n'))

In [9]:
toronto_df = pd.DataFrame({"PostalCode": postalCodeList,
                           "Borough": boroughList,
                           "Neighborhood": neighborhoodList})

toronto_df.head()

  PostalCode           Borough      Neighborhood
0        M1A      Not assigned      Not assigned
1        M2A      Not assigned      Not assigned
2        M3A        North York         Parkwoods
3        M4A        North York  Victoria Village
4        M5A  Downtown Toronto      Harbourfront

In [10]:
toronto_df_dropna = toronto_df[toronto_df.Borough != "Not assigned"].reset_index(drop=True)
toronto_df_dropna.head()

  PostalCode           Borough      Neighborhood
0        M3A        North York         Parkwoods
1        M4A        North York  Victoria Village
2        M5A  Downtown Toronto      Harbourfront
3        M5A  Downtown Toronto       Regent Park
4        M6A        North York  Lawrence Heights

In [17]:
toronto_df_dropna = toronto_df[toronto_df.Borough != "Not assigned"]
toronto_df_dropna.head(25)

   PostalCode           Borough      Neighborhood
2         M3A        North York         Parkwoods
3         M4A        North York  Victoria Village
4         M5A  Downtown Toronto      Harbourfront
5         M5A  Downtown Toronto       Regent Park
6         M6A        North York  Lawrence Heights
7         M6A        North York    Lawrence Manor
8         M7A      Queen's Park      Not assigned
10        M9A         Etobicoke  Islington Avenue
11        M1B       Scarborough             Rouge
12        M1B       Scarborough           Malvern
14        M3B        North York   Don Mills North
15        M4B         East York  Woodbine Gardens
16        M4B         East York     Parkview Hill
17        M5B  Downtown Toronto           Ryerson
18        M5B  Downtown Toronto   Garden District
19        M6B        North York         Glencairn
22        M9B         Etobicoke        Cloverdale
23        M9B         Etobicoke         Islington
24        M9B         Etobicoke      Martin Grove
25        M9B         Etobicoke  Princess Gardens
26        M9B         Etobicoke   West Deane Park
27        M1C       Scarborough    Highland Creek
28        M1C       Scarborough        Rouge Hill
29        M1C       Scarborough        Port Union
31        M3C        North York   Flemingdon Park

In [18]:
toronto_df_grouped = toronto_df_dropna.groupby(["PostalCode", "Borough"], as_index=False).agg(lambda x: ", ".join(x))
toronto_df_grouped.head(25)

   PostalCode      Borough                                       Neighborhood
0         M1B  Scarborough                                     Rouge, Malvern
1         M1C  Scarborough             Highland Creek, Rouge Hill, Port Union
2         M1E  Scarborough                  Guildwood, Morningside, West Hill
3         M1G  Scarborough                                             Woburn
4         M1H  Scarborough                                          Cedarbrae
5         M1J  Scarborough                                Scarborough Village
6         M1K  Scarborough        East Birchmount Park, Ionview, Kennedy Park
7         M1L  Scarborough                    Clairlea, Golden Mile, Oakridge
8         M1M  Scarborough    Cliffcrest, Cliffside, Scarborough Village West
9         M1N  Scarborough                        Birch Cliff, Cliffside West
10        M1P  Scarborough  Dorset Park, Scarborough Town Centre, Wexford ...
11        M1R  Scarborough                                  Maryvale, Wexford
12        M1S  Scarborough                                          Agincourt
13        M1T  Scarborough            Clarks Corners, Sullivan, Tam O'Shanter
14        M1V  Scarborough  Agincourt North, L'Amoreaux East, Milliken, St...
15        M1W  Scarborough                                    L'Amoreaux West
16        M1X  Scarborough                                        Upper Rouge
17        M2H   North York                                  Hillcrest Village
18        M2J   North York                       Fairview, Henry Farm, Oriole
19        M2K   North York                                    Bayview Village
20        M2L   North York                           Silver Hills, York Mills
21        M2M   North York                            Newtonbrook, Willowdale
22        M2N   North York                                   Willowdale South
23        M2P   North York                                    York Mills West
24        M2R   North York                                    Willowdale West

In [19]:
column_names = ["PostalCode", "Borough", "Neighborhood"]
test_df = pd.DataFrame(columns=column_names)

test_list = ["M5G", "M2H", "M4B", "M1J", "M4G", "M4M", "M1R", "M9V", "M9L", "M5V", "M1B", "M5A"]

for postcode in test_list:
    test_df = test_df.append(toronto_df_grouped[toronto_df_grouped["PostalCode"]==postcode], ignore_index=True)
    
test_df

   PostalCode  ...                                       Neighborhood
0         M5G  ...                                 Central Bay Street
1         M2H  ...                                  Hillcrest Village
2         M4B  ...                    Woodbine Gardens, Parkview Hill
3         M1J  ...                                Scarborough Village
4         M4G  ...                                            Leaside
5         M4M  ...                                    Studio District
6         M1R  ...                                  Maryvale, Wexford
7         M9V  ...  Albion Gardens, Beaumond Heights, Humbergate, ...
8         M9L  ...                                      Humber Summit
9         M5V  ...  CN Tower, Bathurst Quay, Island airport, Harbo...
10        M1B  ...                                     Rouge, Malvern
11        M5A  ...                          Harbourfront, Regent Park

[12 rows x 3 columns]

In [20]:
toronto_df_grouped.shape

(103, 3)

In [21]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving Geospatial_Coordinates.csv to Geospatial_Coordinates.csv
User uploaded file "Geospatial_Coordinates.csv" with length 2891 bytes

In [22]:

# load the coordinates from the csv file on Coursera
coordinates = pd.read_csv("Geospatial_Coordinates.csv")
coordinates.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [23]:
coordinates.rename(columns={"Postal Code": "PostalCode"}, inplace=True)
coordinates.head()

  PostalCode   Latitude  Longitude
0        M1B  43.806686 -79.194353
1        M1C  43.784535 -79.160497
2        M1E  43.763573 -79.188711
3        M1G  43.770992 -79.216917
4        M1H  43.773136 -79.239476

In [24]:
toronto_df_new = toronto_df_grouped.merge(coordinates, on="PostalCode", how="left")
toronto_df_new.head()

  PostalCode      Borough  ...   Latitude  Longitude
0        M1B  Scarborough  ...  43.806686 -79.194353
1        M1C  Scarborough  ...  43.784535 -79.160497
2        M1E  Scarborough  ...  43.763573 -79.188711
3        M1G  Scarborough  ...  43.770992 -79.216917
4        M1H  Scarborough  ...  43.773136 -79.239476

[5 rows x 5 columns]

In [25]:
column_names = ["PostalCode", "Borough", "Neighborhood", "Latitude", "Longitude"]
test_df = pd.DataFrame(columns=column_names)

test_list = ["M5G", "M2H", "M4B", "M1J", "M4G", "M4M", "M1R", "M9V", "M9L", "M5V", "M1B", "M5A"]

for postcode in test_list:
    test_df = test_df.append(toronto_df_new[toronto_df_new["PostalCode"]==postcode], ignore_index=True)
    
test_df

   PostalCode           Borough  ...   Latitude  Longitude
0         M5G  Downtown Toronto  ...  43.657952 -79.387383
1         M2H        North York  ...  43.803762 -79.363452
2         M4B         East York  ...  43.706397 -79.309937
3         M1J       Scarborough  ...  43.744734 -79.239476
4         M4G         East York  ...  43.709060 -79.363452
5         M4M      East Toronto  ...  43.659526 -79.340923
6         M1R       Scarborough  ...  43.750072 -79.295849
7         M9V         Etobicoke  ...  43.739416 -79.588437
8         M9L        North York  ...  43.756303 -79.565963
9         M5V  Downtown Toronto  ...  43.628947 -79.394420
10        M1B       Scarborough  ...  43.806686 -79.194353
11        M5A  Downtown Toronto  ...  43.654260 -79.360636

[12 rows x 5 columns]